name: zenrouter_file_annotation
description: "Shared annotation and structure for zenrouter file-based routing."
version: 3.0.0-beta.1
homepage: https://github.com/definev/zenrouter/tree/main/packages/zenrouter_file_annotation
repository: https://github.com/definev/zenrouter/tree/main/packages/zenrouter_file_annotation
resolution: workspace

environment:
  sdk: ^3.7.0
