name: zenrouter
description: >-
  Flutter router. Screens are types; the app is a graph.
  Deep links, web, and a visual route graph.
version: 3.0.0-beta.1

repository: https://github.com/definev/zenrouter
homepage: https://github.com/definev/zenrouter/tree/main/packages/zenrouter
issue_tracker: https://github.com/definev/zenrouter/issues
documentation: https://github.com/definev/zenrouter/blob/main/packages/zenrouter/doc/guides/getting-started.md

topics:
  - router
  - navigation
  - zenrouter
  - state-restoration
  - deep-linking

screenshots:
  - description: "Zen Logo for ZenRouter"
    path: screenshots/logo_light.png

environment:
  sdk: ^3.8.0
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  zenrouter_core: ^3.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
